#!/usr/bin/env bash

usage="$0 [front|bdd]"

if (( $# != 1 ))
then
  echo $usage
  exit 2
fi

if ! type jq
then
  echo "jq tool not installed, use apt, dnf or brew to install it"
  exit 1
fi

public_ip=$( terraform output -json wordpress_${1}_ip | jq -r '.[0]' )

echo "Instance public ip:" ${public_ip}

ssh -i ../ssh-keys/id_rsa_wordpress_common \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    ubuntu@${public_ip}
